boredshopper/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'boredshopper.views.home', name='home'),
    # url(r'^boredshopper/', include('boredshopper.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'bshopper_app.views.ui_index', name='home'),
    #url(r'^homepage_(?P<type>\w+)/(?P<search_query>\w*)$', 'bshopper_app.views.ui_index_with_param', name='ui_index_with_param'),
    url(r'^homepage$', 'bshopper_app.views.ui_index_with_param', name='ui_index_with_param'),
    url(r'old_home^$', 'bshopper_app.views.homepage', name='old_home'),
    (r'^admin/', include(admin.site.urls)),
    (r'^signup/$', 'bshopper_app.views.signup'),
    (r'^login/$', 'django.contrib.auth.views.login', {"template_name": "login.html", }),
    (r'^logout/$', 'django.contrib.auth.views.logout', {"template_name": "logout.html"}),
#    url(r'^login/$', 'bshopper_app.views.login', name='login'),
#    url(r'^logout/$', 'bshopper_app.views.logout', name='logout'),

    (r'^confirm_email/(\w+)/$', 'emailconfirmation.views.confirm_email'),
    url(r'^fbtest/$', 'bshopper_app.views.fbtest', name='fbtest'),
    (r'^facebook/', include('django_facebook.urls')),
    url(r'^user_preferences/$', 'bshopper_app.views.user_preferences', name='user_preferences    '),

    url(r'^accounts/password/reset/$', 'django.contrib.auth.views.password_reset',
            {'post_reset_redirect' : '/accounts/password/reset/done/'}, name='password_reset'),
    url(r'^accounts/password/reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    url(r'^accounts/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',
            {'post_reset_redirect' : '/accounts/password/done/'}),
    url(r'^accounts/password/done/$', 'django.contrib.auth.views.password_reset_complete'),
    (r'^mailchimp/', include('mailchimp.urls')),

    url(r'^ajax_signup', 'bshopper_app.views.ajax_signup', name="ajax_signup"),
    url(r'^ajax_login', 'django.contrib.auth.views.ajax_login', name="ajax_login"),
    url(r'^ajax_logout/$', 'django.contrib.auth.views.ajax_logout', name='ajax_logout'),
    url(r'^ajax_share_send/$', 'bshopper_app.views.ajax_share_send', name='ajax_share_send'),
    url(r'^ajax_acc_welcome/$', 'bshopper_app.views.ajax_acc_welcome', name='ajax_acc_welcome'),
    url(r'^user_setting/$', 'bshopper_app.views.user_setting', name='user_setting'),
    url(r'^user_setting_ajax_get_Manufacturer/$', 'bshopper_app.views.user_setting_ajax_get_Manufacturer', name='user_setting_ajax_get_Manufacturer'),
    #url(r'^wall_post_ajax/$', 'django_facebook.example_views.wall_post_ajax', name='facebook_wall_post_ajax'),
    #url(r'^BShopperServices_getProducts/(?P<product_type>\w+)/(?P<pageNo>\d+)/(?P<min_price>\w+)/(?P<max_price>\w+)/(?P<brand>\w+)/(?P<categories>\w+)/(?P<color>\w+)/$', 'bshopper_app.views.BShopperServices_getProducts', name='BShopperServices_getProducts'),
    url(r'^BShopperServices_getProducts/$', 'bshopper_app.views.BShopperServices_getProducts', name='BShopperServices_getProducts'),
    #url(r'^BShopperServices_getSimilarProducts/(?P<productId>\d+)/(?P<pageNo>\d+)/$', 'bshopper_app.views.BShopperServices_getSimilarProducts', name='BShopperServices_getSimilarProducts'),
    url(r'^ajax_product_like_dislike/$', 'bshopper_app.views.ajax_product_like_dislike', name='ajax_product_like_dislike'),
    url(r'^products/(?P<productId>\d+)/$', 'bshopper_app.views.product_details', name='product_details'),

    #url(r'^new_index', ('bshopper_app.views.ui_index')),
    url(r'^new_page_2col', ('bshopper_app.views.ui_page_2col')),
    url(r'^new_users_setting', ('bshopper_app.views.ui_users_setting')),
    (r'^share/', include('share.urls')),
)

django_facebook/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url
from django.conf import settings

urlpatterns = patterns('django_facebook.views',
                       url(r'^connect/$', 'connect', name='facebook_connect'),
                       url(r'^disconnect/$',
                           'disconnect', name='facebook_disconnect'),
                       url(r'^example/$', 'example', name='facebook_example'),
                       )

dev_patterns = patterns('django_facebook.example_views',
                        url(
                            r'^lazy_decorator_example/$', 'lazy_decorator_example',
                        name='facebook_lazy_decorator_example'),
                        url(r'^decorator_example/$', 'decorator_example',
                            name='facebook_decorator_example'),
                        url(
                            r'^decorator_example_scope/$', 'decorator_example_scope',
                            name='facebook_decorator_example_scope'),
                        url(r'^wall_post/$',
                            'wall_post', name='facebook_wall_post'),
                        #url(r'^wall_post_ajax/$',
                        #    'wall_post_ajax', name='facebook_wall_post_ajax'),
                        url(r'^checkins/$',
                            'checkins', name='facebook_checkins'),
                        url(r'^image_upload/$',
                            'image_upload', name='facebook_image_upload'),
                        url(r'^canvas/$', 'canvas', name='facebook_canvas'),
                        url(r'^page_tab/$',
                            'page_tab', name='facebook_page_tab'),
                        url(r'^open_graph_beta/$', 'open_graph_beta',
                            name='facebook_open_graph_beta'),
                        url(r'^remove_og_share/$', 'remove_og_share',
                            name='facebook_remove_og_share'),
                        )

# when developing enable the example views
if settings.DEBUG or True:
    # only enable example views while developing
    urlpatterns += dev_patterns

# help autodiscovery a bit
from django_facebook import admin

# putting this here instead of models.py reduces issues with import ordering
if getattr(settings, 'AUTH_PROFILE_MODULE', None) == 'django_facebook.FacebookProfile':
    '''
    If we are using the django facebook profile model, create the model
    and connect it to the user create signal
    '''

    from django.db.models.signals import post_save
    from django_facebook.models import FacebookProfile
    from django_facebook.utils import get_user_model

    # Make sure we create a FacebookProfile when creating a User
    def create_facebook_profile(sender, instance, created, **kwargs):
        if created:
            FacebookProfile.objects.create(user=instance)

    post_save.connect(create_facebook_profile, sender=get_user_model())

mailchimp/urls.py
from django.conf.urls.defaults import *
from mailchimp.settings import VIEWS_INFO, VIEWS_OVERVIEW, VIEWS_SCHEDULE_OBJECT, VIEWS_TEST_OBJECT
from mailchimp.views import webhook, dequeue, cancel, test_real

urlpatterns = patterns('',
    url(r'^$', VIEWS_OVERVIEW, name='mailchimp_overview', kwargs={'page':'1'}),
    url(r'^(?P<page>\d+)/$', VIEWS_OVERVIEW, name='mailchimp_overview'),
    url(r'^send/(?P<content_type>\d+)/(?P<pk>\d+)/$', VIEWS_SCHEDULE_OBJECT, name='mailchimp_schedule_for_object'),
    url(r'^test/(?P<content_type>\d+)/(?P<pk>\d+)/$', VIEWS_TEST_OBJECT, name='mailchimp_test_for_object'),
    url(r'^test/(?P<content_type>\d+)/(?P<pk>\d+)/real/$', test_real, name='mailchimp_real_test_for_object'),
    url(r'^info/(?P<campaign_id>\w+)/$', VIEWS_INFO, name='mailchimp_campaign_info'),
    url(r'^dequeue/(?P<id>\d+)/', dequeue, name='mailchimp_dequeue'),
    url(r'^cancel/(?P<id>\d+)/', cancel, name='mailchimp_cancel'),
    url(r'^webhook/(?P<key>\w+)/', webhook, name='mailchimp_webhook'),
)

share/urls.py
from django.conf.urls.defaults import patterns, url
from share.views import EmailFormView

urlpatterns = patterns('',
  url(r'^email/$', EmailFormView.as_view(), name='share_email'),
)

bshopper_app/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django_facebook.models import FacebookCustomUser as User
from datetime import datetime
from django.core.mail import send_mail
from django.template.loader import get_template
from django.template import Context

GENDER_CHOICES = (
    ('m', 'Male'),
    ('f', 'Female'),
    ('n', 'Null'),
)
import os
PROFILE_IMAGE_PATH = os.path.join('uploads', 'profile_pictures/%Y/%m/%d')

class Categories(models.Model):
    """
    """
    CatId = models.AutoField(primary_key=True)
    Category_name = models.CharField(max_length=150,blank=True, null=True)
    Category_name_hier = models.CharField(max_length=150,blank=True, null=True)
    Gender = models.CharField(max_length=1)
    class Meta:
        db_table = "bshopper_app_categories"
        verbose_name = "Categorie"
        #verbose_name_plural = "Categories"
    def __str__(self):
        return "%s -- %s" % (self.CatId, self.Category_name)
#    def __unicode__(self):
#        return self.Category_name

class ScrapedItems(models.Model):
    """
    scraped_items
    """
    id = models.AutoField(primary_key=True)
    url = models.CharField(max_length=750, blank=True, null=True)
    sku = models.CharField(max_length=150, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    manufacturer = models.CharField(max_length=750, blank=True, null=True)
    scraped_category = models.CharField(max_length=750, blank=True, null=True)
    color = models.CharField(max_length=750, blank=True, null=True)
    size = models.CharField(max_length=750, blank=True, null=True)
    title = models.CharField(max_length=750, blank=True, null=True)
    retail_price = models.CharField(max_length=750, blank=True, null=True)
    sale_price = models.CharField(max_length=750, blank=True, null=True)
    _type = models.CharField(max_length=100, blank=True, null=True)
    image_urls = models.CharField(max_length=3000, blank=True, null=True)
    images = models.CharField(max_length=3000, blank=True, null=True)
    images_json = models.CharField(max_length=3000, blank=True, null=True)
    project_id = models.CharField(max_length=100, blank=True, null=True)
    job_id = models.CharField(max_length=100, blank=True, null=True)
    timestamp = models.DateTimeField(blank=True, null=True)
    spider_name = models.CharField(max_length=100, blank=True, null=True)
    predicted_category_name = models.CharField(max_length=750, blank=True, null=True)
    #predicted_category_id = models.IntegerField()
    predicted_category = models.ForeignKey(Categories)
    duplication_check = models.CharField(max_length=100, blank=True, null=True)
    class Meta:
        db_table = "scraped_items"
        verbose_name = "Scraped item"
        #verbose_name_plural = "Scraped items"

class FacebookAuth(models.Model):
    """
    Facebook auth

    user id
    facebook id
    product page likes
    linked date
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    FacebookId = models.CharField(max_length=200)
    ProductPageLikes = models.CharField(max_length=1000)
    LinkedDate = models.DateTimeField(blank=True, null=True)

class MailChimp(models.Model):
    """
    Facebook auth

    user id
    facebook id
    product page likes
    linked date
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    MailChimpAllowed = models.BooleanField(default=True)

class UserPreferences(models.Model):
    """
    User preferences

    user id
    first name
    last name
    gender
    birthday
    profile picture path
    location
    categories (comma seperated)
    brands (comma seperated)
    price (comma seperated)
    color (comma seperated)
    """


    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    FirstName = models.CharField(max_length=100,blank=True, null=True)
    LastName = models.CharField(max_length=100,blank=True, null=True)
    Gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    BirthDay = models.DateField(blank=True, null=True)

    ProfilePicturePath = models.ImageField(upload_to=PROFILE_IMAGE_PATH, blank=True)
    Location = models.CharField(max_length=200)
    Categories = models.CharField(max_length=1000)
    Brands = models.CharField(max_length=1000)
    Price = models.CharField(max_length=1000)
    Color = models.CharField(max_length=1000)
    class Meta:
        verbose_name = "User preference"
        #verbose_name_plural = "User preferences"


class Manufacturer(models.Model):
    """
    """
    Manufacturer_id = models.AutoField(primary_key=True)
    Manufacturer_Name = models.CharField(max_length=150,blank=True, null=True)
    class Meta:
        db_table = "Manufacturer"

class User_Viewership(models.Model):
    """
    """
    RowID = models.AutoField(primary_key=True)
    UserId = models.IntegerField()
    ProductId = models.IntegerField()
    LikeProduct = models.IntegerField()
    NoOfViews = models.IntegerField()
    class Meta:
        db_table = "bshopper_user_viewership"

class Trending_Products(models.Model):
    """
    """
    id = models.AutoField(primary_key=True)
    ProductId = models.IntegerField()
    UserId = models.IntegerField()
    #TransactionDate = models.DateTimeField(blank=True, null=True)
    TransactionDate = models.DateTimeField(default=datetime.now())
    class Meta:
        db_table = "bshopper_trending_products"

class Merchants(models.Model):
    """
    """
    id = models.AutoField(primary_key=True)
    merch_id = models.CharField(max_length=250,blank=True, null=True)
    merch_name = models.CharField(max_length=250,blank=True, null=True)
    class Meta:
        db_table = "bshopper_app_merchants"

class Product_Color(models.Model):
    """
    """
    ProductId = models.AutoField(primary_key=True)
    image = models.CharField(max_length=500,blank=True, null=True)
    Color = models.CharField(max_length=500,blank=True, null=True)
    Hex = models.CharField(max_length=20,blank=True, null=True)
    rgb = models.CharField(max_length=20,blank=True, null=True)
    class Meta:
        db_table = "bshopper_product_color"

class Top_Manufacturer(models.Model):
    """
    """
    Manufacturer_Id = models.AutoField(primary_key=True)
    Manufacturer = models.CharField(max_length=300,blank=True, null=True)
    class Meta:
        db_table = "bshopper_top_brands"

class Invitation(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=500,blank=True, null=True)
    code = models.CharField(max_length=20)
    sender = models.ForeignKey(User)

    def __unicode__(self):
        return u'%s, %s' % (self.sender.username, self.email)
    def send(self):
        subject = u'Invitation to join Django Bookmarks'
        link = 'http://%s/friend/accept/%s/' % ("www.boredshopper.com", self.code)
        template = get_template('invitation_email.txt')
        context = Context({
            'name': self.name,
            'link': link,
            'sender': self.sender.username,
            })
        message = template.render(context)
        send_mail(
            subject, message,
            settings.DEFAULT_FROM_EMAIL, [self.email]
        )
    class Meta:
        db_table = "bshopper_email_invitation"

templates/UI/base-old.html
<!DOCTYPE html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8"/>
        <title>{% block head_title %}{% endblock %}</title>

        <link href="{{ STATIC_URL }}stylesheets/custom.css" type="text/css" rel="stylesheet" media="all" />

        <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
        <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    </head>
    <body>
        <header>
            <div class="row">
                <a href="/" style="color: black;text-decoration: none;"><h1>Bored Shopper Home Page</h1></a>
                <a href="/">home</a>&nbsp;&nbsp;&nbsp;
                {% if user.is_authenticated %}
                    <a href="/logout/">logout</a>
                {% else %}
                    <a href="/login/">login</a>
                {% endif %}
            </div>
        </header>
        <hr/>
        {% block body_content %}
        {% endblock %}

        <br/><br/><br/><hr/>
        <footer style="margin-top:10px;">
            <div class="row">
                <div class="colums">
                    <p>&copy; 2013 Bored Shopper. All Rights Reserved.</p>
                </div>
            </div>
        </footer>
    </body>
</html>

templates/UI/form_field.html
<div class="myformfield{% if field.field.required %} required{% endif %}{% if field.errors %} error{% endif %}">
      {{ field.errors }}
      {% if field.is_checkbox %}
          {{ field }}{{ field.label_tag }}
      {% else %}
          {{ field.label_tag }}{{ field }}
      {% endif %}
      {% if field.help_text %}<p class="help">{{ field.help_text }}</p>{% endif %}
</div>

templates/UI/homepage.html
{% extends "base.html" %}

{% block head_title %}Bored Shopper{% endblock %}

{% block body_content %}
{% if user.is_authenticated %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<p>Logged in as {{ user.email }}.</p>
<ul>
    <li><a href="/logout/">logout</a></li>
    <li><a href="/user_preferences/">Edit User Preferences</a></li>
</ul>

<ul class="user_preferences_list">
<li>
    <span class="left_side">First Name : </span>
    <span class="right_side">{{ user.userpreferences_set.all.0.FirstName }}</span>
</li>
<li>
    <span class="left_side">Last Name : </span>
    <span class="right_side">{{ user.userpreferences_set.all.0.LastName }}</span>
</li>
<li>
    <span class="left_side">Gender : </span>
    <span class="right_side">{{ user.userpreferences_set.all.0.Gender }}</span>
</li>
<li>
    <span class="left_side">FirstName : </span>
    <span class="right_side">{{ user.userpreferences_set.all.0.FirstName }}</span>
</li>
<li>
    <span class="left_side">Birth Day : </span>
    <span class="right_side">{{ user.userpreferences_set.all.0.BirthDay }}</span>
</li>
<li>
    <span class="left_side" style="float: left;">Profile Picture Path : </span><br/>
    {% if user.userpreferences_set.all.0.ProfilePicturePath %}
    <img src="{{ STATIC_URL }}../../bshopper_app/media/{{ user.userpreferences_set.all.0.ProfilePicturePath }}" alt="" style="width:150px;float: left;"/>
    {% endif %}
    </span>
</li>
<br/>
<li style="clear: both;">
    <span class="left_side" style="">Location : </span>
    <span class="right_side">{{ user.userpreferences_set.all.0.Location }}</span>
</li>
<li>
    <span class="left_side">Categories : </span>
    <span class="right_side">{{ user.userpreferences_set.all.0.Categories }}</span>
</li>
<li>
    <span class="left_side">Brands : </span>
    <span class="right_side">{{ user.userpreferences_set.all.0.Brands }}</span>
</li>
<li>
    <span class="left_side">Price : </span>
    <span class="right_side">{{ user.userpreferences_set.all.0.Price }}</span>
</li>
<li>
    <span class="left_side">Color : </span>
    <span class="right_side">{{ user.userpreferences_set.all.0.Color }}</span>

</li>
</ul>

{% else %}
<p>Not logged in.</p>
<ul>
    <li><a href="/signup/">signup</a></li>
    <li><a href="/login/">login</a></li>
</ul>
{% endif %}
{% endblock %}

templates/UI/login.html
{% extends "base.html" %}

{% block head_title %}Login{% endblock %}

{% block body_content %}
    {% if form.errors %}
        <p class="error">Please correct the errors below:</p>
    {% endif %}
    
    <form method="POST" action="">{% csrf_token %}
        <dl>
            {{ form.non_field_errors }}
            <dt><label for="id_username">Username(email):</label>{% if form.username.errors %} <span class="error">{{ form.username.errors|join:", " }}</span>{% endif %}</dt>
            <dd>{{ form.username }}</dd>
            <dt><label for="id_password">Password:</label>{% if form.password.errors %} <span class="error">{{ form.password.errors|join:", " }}</span>{% endif %}</dt>
            <dd>{{ form.password }}</dd>
            <dt><input type="submit" value="Log in" /></dt>

            <p style="margin-left:114px;">
                <a href="{% url 'password_reset' %}">Forgot password?</a>
            </p>
        </dl>
    </form>

    <!--form to call registration via facebook -->
    <form action="{% url 'facebook_connect' %}" method="post">
        <h2>Register, login or connect with Facebook</h2>
        <br />
        {% csrf_token %}
        <input type="hidden" value="/" name="next" />

        <!--
        use error next for a seperate error page
        <input type="hidden" value="/error/" name="error_next" />
        -->
        <div id="facebook_login_js">
        <input onclick="F.connect(this.parentNode.parentNode); return false;" type="image" src="{{ STATIC_URL }}images/b_signin_facebook_small.png" /><br />
        </div>
    </form>


    <script src="{{ STATIC_URL }}js/statictest.js" type="text/javascript"></script>

    {% include 'django_facebook/_facebook_js.html' %}

{% endblock %}

templates/UI/logout.html
{% extends "base.html" %}

{% block head_title %}Logout{% endblock %}

{% block body_content %}
<p>You've been logged out. Return to <a href="/">homepage</a>.</p>
{% endblock %}

templates/UI/mailchimp_register_test.html
{% extends "base.html" %}

{% block head_title %}Test Mailchimp Forms{% endblock %}

{% block body_content %}
<form method="post" action="" class="singupform">{% csrf_token %}
<table>{{ form.as_table }}</table>
<input type="submit" value="signup"/>
</form>
{% endblock %}

templates/UI/page-2col.html
{% extends "base.html" %}

{% block head_title %}Bored Shopper{% endblock %}

{% block body_content %}
<div class="clear"></div>
<div class="spacer"></div>
<!--bodyarea starts-->
<div class="bodyarea">
  <div class="breadcrumb"><a href="#">Home</a> &raquo; <a href="#">Products</a> &raquo; <a class="breadcrumb_active" href="#">Details</a></div>
  <div class="content-2col">
    <div class="sidebar">
      <div class="widget">
        <h3 class="widget-title">Content Title </h3>
        <ul>
          <li>Lorem ipsum is dummy text</li>
          <li>Lorem ipsum is dummy text</li>
          <li>Lorem ipsum is dummy text</li>
          <li>Lorem ipsum is dummy text</li>
          <li>Lorem ipsum is dummy text</li>
        </ul>
      </div>
      <div class="widget">
        <h3 class="widget-title">Content Title</h3>
        <p>Lorem ipsum dolor sit amet, eos amet munere eu, eu amet complectitur qui, veri maluisset eu cum. Vim prima bonorum adipiscing eu, fabulas commune mediocritatem mei an. Cu vitae everti pro. Ad nonumes sensibus pro. Rebum interpretaris ut mel, odio qualisque incorrupte duo ea.</p>
      </div>
      <div class="widget">
        <h3 class="widget-title">Content Title </h3>
        <ul>
          <li>Lorem ipsum is dummy text</li>
          <li>Lorem ipsum is dummy text</li>
          <li>Lorem ipsum is dummy text</li>
          <li>Lorem ipsum is dummy text</li>
          <li>Lorem ipsum is dummy text</li>
        </ul>
      </div>
    </div>
    <div class="content-right">
      <h1>Page Title</h1>
      <p>Lorem ipsum dolor sit amet, eos amet munere eu, eu amet complectitur qui, veri maluisset eu cum. Vim prima bonorum adipiscing eu, fabulas commune mediocritatem mei an. Cu vitae everti pro. Ad nonumes sensibus pro. Rebum interpretaris ut mel, odio qualisque incorrupte duo ea.</p>
      <p> Nec an noster audire latine, et sea reque vidisse scriptorem, ne appareat ponderum reprehendunt qui. No saperet vituperata est, ex sed hinc vidisse vivendo. At euripidis adolescens eam. Prompta repudiare qui et, mucius delenit sed ei. </p>
      <p> Has te putent menandri, noster fastidii accusamus qui ex. Soluta doming pri te, pri noster electram interesset id, virtute blandit et sit. Quo autem regione labitur ex, an mea elitr abhorreant. Ut legere reformidans vim, ne minimum comprehensam mel. Mazim soluta ut nec, at erat habeo perpetua mei, cu error aliquam mei. </p>
      <p>Est vocibus constituto ne, te modo facilisi consequat sed. Nobis tollit doctus id vel, sea te sint facilisis hendrerit. Eos sumo mazim ut. Sed sale mediocritatem ut, ad suas quot eam. </p>
      <p> Duo labitur mentitum appetere ea, zril volumus deserunt et his. Sea et error nullam, ex debitis volutpat similique qui. Vel aperiri blandit scriptorem ne, tractatos dissentias per te. Omnes menandri vel ad, vis at adolescens constituam, cum vulputate adipiscing ex. Cu tacimates erroribus usu, congue vocibus an mel.</p>
    </div>
  </div>
</div>
<!--bodyarea ends-->
<div class="clear"></div>
<!--footer starts here-->
<div class="footer">
  <div class="copyright">Copyright&copy; All Rights Reserved.</div>
  <div class="footer_link"><a href="#">Home</a> <a href="#">About</a> <a href="#">Products</a> <a href="#">Services</a> <a href="#">Contact</a> </div>
</div>
<!--footer ends here-->
{% endblock %}

templates/UI/signup.html
{% extends "base.html" %}

{% block head_title %}Signup{% endblock %}

{% block body_content %}
<form method="post" action="" class="singupform">{% csrf_token %}
<table>{{ form.as_table }}</table>
<input type="submit" value="signup"/>
</form>
{% endblock %}

templates/UI/user_preferences.html
{% extends "base.html" %}

{% block head_title %}User Preferences{% endblock %}

{% block body_content %}
<form method="post" action="{% url 'user_preferences' %}" class="user_preference" enctype="multipart/form-data">{% csrf_token %}
   {% with form.FirstName as field %}
        {% include 'form_field.html' %}
   {% endwith %}

   {% with form.LastName as field %}
        {% include 'form_field.html' %}
   {% endwith %}

   {% with form.Gender as field %}
        {% include 'form_field.html' %}
   {% endwith %}

   {% with form.BirthDay as field %}
        {% include 'form_field.html' %}
   {% endwith %}

   <div class="required{% if form.ProfilePicturePath.errors %} errors{% endif %}">
        {{ form.ProfilePicturePath.errors }}
        <table width="75%">
        <tr>
            <td colspan='2'>{{ form.ProfilePicturePath.label_tag }}</td>
        </tr>
        <tr>
            <td id="ProfilePicturePath">
                <span class="right_side">
                    {% if user.userpreferences_set.all.0.ProfilePicturePath %}
                    <img src="{{ STATIC_URL }}../../bshopper_app/media/{{ user.userpreferences_set.all.0.ProfilePicturePath }}" alt="" style="width:150px;margin-left: 50px;"/>
                    {% endif %}
                </span>
                {{ form.ProfilePicturePath }}
            </td>
            <td>{{ form.ProfilePicturePath.help_text }}</td>
        </tr>
        </table>
   </div>

   {% with form.Location as field %}
        {% include 'form_field.html' %}
   {% endwith %}

   {% with form.Categories as field %}
        {% include 'form_field.html' %}
   {% endwith %}

   {% with form.Brands as field %}
        {% include 'form_field.html' %}
   {% endwith %}

   {% with form.Price as field %}
        {% include 'form_field.html' %}
   {% endwith %}

   {% with form.Color as field %}
        {% include 'form_field.html' %}
   {% endwith %}

    <div><input type="submit" value="Save" style="margin-left: 200px;"/></div>
</form>

<script type="text/javascript">
function render_img()
{
    //$('.user_preference ').prepend('<img id="theImg" src="theImg.png" />')
    $('#ProfilePicturePath a').css('display', 'none');
    str = $('#ProfilePicturePath').innerHTML;
    str = str.replace("Currently: ", "");
    $('#ProfilePicturePath').innerHTML = "str";
}
$(document).ready(function(){
    render_img();
});

</script>
{% endblock %}